// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
=======
using Microsoft.EntityFrameworkCore.Metadata;
>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProchocBackend.Database;

namespace ProchocBackend.Migrations
{
    [DbContext(typeof(ProchocDbContext))]
    partial class ProchocDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");
=======
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs

            modelBuilder.Entity("ProchocBackend.Database.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                        .HasColumnType("int");
=======
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
=======
                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Baskets");
                });

<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
            modelBuilder.Entity("ProchocBackend.Database.BasketProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("BasketId")
=======
            modelBuilder.Entity("ProchocBackend.Database.BasketEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("ProchocBackend.Database.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ProchocBackend.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");
=======
                    b.ToTable("BasketEntries");
                });

            modelBuilder.Entity("ProchocBackend.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProchocBackend.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                });

            modelBuilder.Entity("ProchocBackend.Database.Basket", b =>
                {
<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                    b.HasOne("ProchocBackend.Database.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProchocBackend.Database.BasketProduct", b =>
                {
                    b.HasOne("ProchocBackend.Database.Basket", "Basket")
                        .WithMany()
=======
                    b.HasOne("ProchocBackend.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProchocBackend.Database.BasketEntry", b =>
                {
                    b.HasOne("ProchocBackend.Database.Basket", null)
                        .WithMany("Products")
>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                        .HasForeignKey("BasketId");

                    b.HasOne("ProchocBackend.Database.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

<<<<<<< Updated upstream:ProchocBackend/ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
                    b.Navigation("Basket");

                    b.Navigation("Product");
                });
=======
                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProchocBackend.Database.Basket", b =>
                {
                    b.Navigation("Products");
                });
>>>>>>> Stashed changes:ProchocBackend/Migrations/ProchocDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
